import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
/* @ts-ignore */
import "./globals.css";
import FooterProvider from "@/components/FooterProvider";


const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakartaSans.variable} bg-black text-white antialiased`}
      >
        <FooterProvider>
          {children}
        </FooterProvider>
      </body>
    </html>
  );
}
